#pragma once
enum class ActivityType
{
    VOID = 0U,
    STD_CLASS_0_1_IO = 1U,
    CLASS0_AGGREGATED = 2U,
    STD_CLASS3_CONFIG = 3U,
    MOTION_CLASS3_IO = 4U,
    SAFETY_CLASS0_IO = 5U,
    NULL_RACK_OPTIMIZED = 6U,
    NULL_ADC_SIGNATURE_CHECK = 7U,
    PING = 8U,
    UNCONN_MSG = 9U
};